require 'bundler'
Bundler.require

require 'opal'
require 'opal/rspec/rake_task'
require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new(:spec)

namespace :opal do
  desc "Build ruby2600.js"
  task :build do
    env = Opal::Environment.new
    env.append_path "bin"
    env.append_path "lib"

    File.open("ruby2600.js", "w+") do |out|
      out << env["ruby2600-opal"].to_s
    end
  end

  Opal.append_path File.expand_path('../lib', __FILE__)

  Opal::RSpec::RakeTask.new(:spec)
end

namespace :spec do
  desc "Regenerate spec/fixtures/cart_arrays.rb from spec/fixtures/files/*.bin"
  task :cart_arrays do
    ruby_filename = 'spec/fixtures/cart_arrays.rb'
    contents = "\# Generated by rake spec:cart_arrays. DO NOT EDIT, YOU WILL LOSE IT.\n\n"
    Dir['spec/fixtures/files/*.bin'].each do |filename|
      array = File.open(filename, "rb") { |f| f.read }.unpack('C*')
      contents << "#{File.basename(filename, '.bin')}_cart_array = #{array}\n".upcase
    end
    puts "Generating #{ruby_filename}"
    File.open(ruby_filename, 'w') {|f| f.write(contents) }
  end
end

task :default => :spec
